<!DOCTYPE html>
<html>
<head>
	<title>Страница обратной связи</title>
	<meta charset="utf-8">
    <link rel='stylesheet' href='styles.css' type='text/css'>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<script type="text/javascript" 
		src="https://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" 
		src="https://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
</head>
<body>

<div class="area_wrap">

<div class="contactform">
<h3 style="text-align:center">Введите контактные данные</h3>
<form action="<?= $_SERVER['PHP_SELF']; ?>" method="post">
<div class='field'>
	<label><span>E-mail</span></label>
	<span class="error"><?= $error['email'] ?? "*";?></span>
	<input type="email" name="email" value="<?= html($user['email'])?>" >
	
</div>
<div class='field'>
	<label><span>ФИО</span></label>
	<span class="error"><?= $error['fio'] ?? "*";?></span>
	<input type="text" name="fio" value="<?= html($user['fio'])?>" >	
</div>
<div class='field'>
	<label><span>Телефон</span></label>
	<span class="error"><?= $error['phone'] ?? "*";?></span>
	<input type="text" name="phone" value="<?= html($user['phone'])?>" >
</div>
<div class='field'>
	<label><span>Адрес</span></label> 
	<span class="error"><?= $error['address'] ?? "*";?></span>
	<input type="text" name="address" value="<?= html($user['address'])?>" >
</div>
<div class='button'>
	<input class="redlabel" type="submit" value="Отправить" >
</div>
<?= $regString;?>
</form>
</div>

<?php if ($validation): ?>
<?php include '../views/usertable.phtml'; ?>
<?php endif; ?>


</div>


</body>