<!DOCTYPE html>
<html>
<head>
	<title>Страница новостей</title>
	<meta charset="utf-8" >
	<link rel='stylesheet' href='styles.css' type='text/css'>
</head>
<body>
	<?php if ($result): ?>
	  <?php foreach ($result as $news): ?>
		<div class='news'>
		<?= html($news['title']) ?>
		<br>
		<?= html($news['datetime']) ?>
		<br>
		<?= html($news['description']) ?>
		</div>
	  <?php endforeach; ?>	
	<?php endif; ?>	
</body>